console.log('hello world');
console.log(1234567);
console.log(false);
var greeting = "안녕하세요";
console.log(greeting);
console.log({a:'a', b:'b'});
console.table({a:'a', b:'b'});
console.error('Error!');
console.warn('Warning!');
console.time('hello');
console.log(1);
console.log(2);
console.log(3);
console.log(4);
console.log(5);
console.log(6);
console.log(7);
console.timeEnd('hello');

console.clear();
